// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCufnhW5TAlCq9V8kE4eDwcyxDb2sO2tfA',
    appId: '1:240729793143:web:27cf45a3a95df367f59c72',
    messagingSenderId: '240729793143',
    projectId: 'kavir-app-project',
    authDomain: 'kavir-app-project.firebaseapp.com',
    storageBucket: 'kavir-app-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxJ51yYl0icMHK-1ho_vPlPADe_uUIieE',
    appId: '1:240729793143:android:3a6450ae76c2045ff59c72',
    messagingSenderId: '240729793143',
    projectId: 'kavir-app-project',
    storageBucket: 'kavir-app-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs3jBD56M98tdUJFs_W2YPgnGMH2adO6c',
    appId: '1:240729793143:ios:39723caa0c76d498f59c72',
    messagingSenderId: '240729793143',
    projectId: 'kavir-app-project',
    storageBucket: 'kavir-app-project.appspot.com',
    iosClientId: '240729793143-siqptkpaiq6lar59702igps0aiehp7n5.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs3jBD56M98tdUJFs_W2YPgnGMH2adO6c',
    appId: '1:240729793143:ios:d493bfc52154e620f59c72',
    messagingSenderId: '240729793143',
    projectId: 'kavir-app-project',
    storageBucket: 'kavir-app-project.appspot.com',
    iosClientId: '240729793143-7c6mj48uq11m6d1voefiubhel0111ome.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApp.RunnerTests',
  );
}
